name: Generate EPG every day
on:
  schedule:
    - cron: '00 00-16/4 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: config
        run: |
          git pull
          git config --global user.email "warningfm@gmail.com"
          git config --global user.name "warningfm"
      - name: generate
        run: |
          cd epg
          pwd
          [ ! -d global ] && mkdir -v global/
          [ ! -d local ] && mkdir -v local/
          python3 -m pip install lxml
          echo "Generating EPG for main playlist..."
          python3 scripts/index.py guide.xml scripts/main/main.txt "iptv.nng.cloudns.us Playlist" "iptv.nng.cloudns.us"
          gzip -9 guide.xml
          mv -v guide.xml.gz global/
          echo "Generating EPG for local playlist..."
          python3 scripts/index.py guide.xml scripts/local/local.txt "iptv.nng.cloudns.us Playlist" "iptv.nng.cloudns.us"
          mv -v guide.xml local/
          cd ..
      - name: commit
        run: |
          git add -A
          git commit -m "Generate EPG every day"
          git push
