name: Update Youtube streams
on:
  schedule:
    - cron: '00 00/1 * * *'
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      - name: config
        run: |
          git pull
          git config --global user.email "warningfm@gmail.com"
          git config --global user.name "warningfm"
      - name: update streams
        run: |
          pwd
          mkdir tmp
          wget -U okhttp/1.2 -qP tmp http://103.152.118.53:80/api/yt/index.py
          python3 tmp/index.py --url "https://www.youtube.com/c/aquariusmusikindo/live" live/m3u8/ytb/akuarius.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/channel/UCcZg5r9hBqK_VPUT2I7eYVw/live" live/m3u8/ytb/Bernama.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/c/musicastudios/live" live/m3u8/ytb/musika.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/nagaswarafmbgr/live" live/m3u8/ytb/nagaswaradensdut.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/watch?v=Gvfr_OoTp1E" live/m3u8/ytb/nagaswarakoplo.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/watch?v=Is03gZsBeq0" live/m3u8/ytb/nagaswarapop.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/watch?v=Qk-QnFxIZ88" live/m3u8/ytb/nagaswarareligi.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/c/kompastv/live" live/m3u8/ytb/ae5f9d6bcd610b6.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/@metrotvnews/live" live/m3u8/ytb/6183ec225226ccc.m3u8
          sleep 3
          python3 tmp/index.py --url "https://www.youtube.com/c/tvonenews/live" live/m3u8/ytb/0976f879a0c4548.m3u8
          rm -rf tmp
      - name: commit
        run: |
          git add -A
          git commit -m "Update Youtube streams"
          git push
